@baseUrl = http://localhost:3000

###

GET {{baseUrl}}/courses

###

GET {{baseUrl}}/courses/1


###

POST {{baseUrl}}/courses/
Content-Type: application/json; charset=utf-8

{
  "id": 2,
  "name": "Curso Nest.js",
  "description": "Nest.js Completo",
  "price": 50.99
}

###

PATCH {{baseUrl}}/courses/3
Content-Type: application/json; charset=utf-8

{
  "id": 2,
  "name": "Curso Vue.js",
  "description": "Vue.js Completo",
  "tags": ["vue"]
}

###

DELETE {{baseUrl}}/courses/3
