
###

GET http://localhost:3000/courses

###

GET http://localhost:3000/courses/4


###

POST http://localhost:3000/courses
Content-Type: application/json; charset=utf-8

{
  "name": "Curso Nest.js",
  "description": "Nest.js Completo",
  "price": 50.99
}

###

PATCH http://localhost:3000/courses/1
Content-Type: application/json; charset=utf-8

{
  "name": "Curso Nest.js",
  "description": "Nest.js Completo",
  "price": 50.99
}

###

DELETE http://localhost:3000/courses/1
